In [1]:
import pandas as pd

df = pd.read_pickle('./train.pkl')

In [2]:
df

user     item  rating      timestamp    type
0               0   305831       1  1659370027105  orders
1               0   461689       1  1659370027105  orders
2               0  1199474       1  1661552940651  orders
3               0   543308       1  1661552940651  orders
4               3   357461       1  1659390912679  orders
...           ...      ...     ...            ...     ...
5098946  12899373  1766353       1  1661723865480  orders
5098947  12899525  1488793       1  1661723996896  orders
5098948  12899525  1599360       1  1661723996896  orders
5098949  12899525   996393       1  1661723996896  orders
5098950  12899525   956231       1  1661723996896  orders

[5098951 rows x 5 columns]

In [15]:
small_Df = df[df.item.isin(list(df.item.value_counts()[:30000].index))]

In [16]:
small_Df.to_pickle("./small_train.pkl")

In [10]:
list(df.item.value_counts()[:30000].index)

Int64Index([ 231487,  166037, 1733943, 1445562, 1022566,  801774, 1629608,
             756588,  332654, 1603001,
            ...
             943798, 1164330,  367854,  888198, 1363956,  581784,  438955,
            1059698, 1090075, 1613401],
           dtype='int64', length=30000)

In [42]:
import numpy as np
val = [
    [1, 2],
    [1, 3],
    [2, 2],
    [2, 3]
]

val = np.array(val)

In [43]:
val[:, 0]

array([1, 1, 2, 2])

In [44]:
uval = (val[:, 0] == 1) & ((val[:, 1] == 2) | (val[:, 1] == 3))
idx = np.where(uval)
idx

(array([0, 1]),)

In [47]:
np.delete(val, idx, 0)


array([[2, 2],
       [2, 3]])